In [49]:
#import libraries
import pandas as pd

In [50]:
#import dataset
data= pd.read_csv("/content/drinkMenu.csv")

In [51]:
#show dataset
data.head()

,Beverage_category,Beverage,Beverage_prep,Calories,Total Fat (g),Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g),Vitamin A (% DV),Vitamin C (% DV),Calcium (% DV),Iron (% DV),Caffeine (mg)
0,Coffee,Brewed Coffee,Short,3,0.1,0.0,0.0,0,5,0,0,0,0.3,0%,0%,0%,0%,175
1,Coffee,Brewed Coffee,Tall,4,0.1,0.0,0.0,0,10,0,0,0,0.5,0%,0%,0%,0%,260
2,Coffee,Brewed Coffee,Grande,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,0%,0%,330
3,Coffee,Brewed Coffee,Venti,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,2%,0%,410
4,Classic Espresso Drinks,Caffè Latte,Short Nonfat Milk,70,0.1,0.1,0.0,5,75,10,0,9,6.0,10%,0%,20%,0%,75

In [52]:
#show dataset info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Beverage_category          242 non-null    object
 1   Beverage                   242 non-null    object
 2   Beverage_prep              242 non-null    object
 3   Calories                   242 non-null    int64
 4    Total Fat (g)             242 non-null    object
 5   Trans Fat (g)              242 non-null    float64
 6   Saturated Fat (g)          242 non-null    float64
 7    Sodium (mg)               242 non-null    int64
 8    Total Carbohydrates (g)   242 non-null    int64
 9   Cholesterol (mg)           242 non-null    int64
 10   Dietary Fibre (g)         242 non-null    int64
 11   Sugars (g)                242 non-null    int64
 12   Protein (g)               242 non-null    float64
 13  Vitamin A (% DV)           242 non-null    object
 14  Vitamin C (% DV)           242 non-null    object
 15   Calcium (% DV)            242 non-null    object
 16  Iron (% DV)                242 non-null    object
 17  Caffeine (mg)              241 non-null    object
dtypes: float64(3), int64(6), object(9)
memory usage: 34.2+ KB

In [53]:
#check duplicates
v=data.duplicated()
v.value_counts()

False    242
dtype: int64

In [54]:
#To be certain 
duplicateRows = data[data.duplicated()]
duplicateRows

Empty DataFrame
Columns: [Beverage_category, Beverage, Beverage_prep, Calories,  Total Fat (g), Trans Fat (g) , Saturated Fat (g),  Sodium (mg),  Total Carbohydrates (g) , Cholesterol (mg),  Dietary Fibre (g),  Sugars (g),  Protein (g) , Vitamin A (% DV) , Vitamin C (% DV),  Calcium (% DV) , Iron (% DV) , Caffeine (mg)]
Index: []

In [55]:
#data preparation_1

#data.drop_duplicates() #no need to this because there aren't duplicates in the dataset

In [56]:
#data["Caffeine (mg)"].mean()

In [61]:
#data preparation_2
#fill null values
m=data["Caffeine (mg)"].mode()[0]
data["Caffeine (mg)"].fillna(value=m, inplace=True)

In [62]:
#check filling null values
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Beverage_category          242 non-null    object
 1   Beverage                   242 non-null    object
 2   Beverage_prep              242 non-null    object
 3   Calories                   242 non-null    int64
 4    Total Fat (g)             242 non-null    object
 5   Trans Fat (g)              242 non-null    float64
 6   Saturated Fat (g)          242 non-null    float64
 7    Sodium (mg)               242 non-null    int64
 8    Total Carbohydrates (g)   242 non-null    int64
 9   Cholesterol (mg)           242 non-null    int64
 10   Dietary Fibre (g)         242 non-null    int64
 11   Sugars (g)                242 non-null    int64
 12   Protein (g)               242 non-null    float64
 13  Vitamin A (% DV)           242 non-null    object
 14  Vitamin C (% DV)           242 non-null    object
 15   Calcium (% DV)            242 non-null    object
 16  Iron (% DV)                242 non-null    object
 17  Caffeine (mg)              242 non-null    object
dtypes: float64(3), int64(6), object(9)
memory usage: 34.2+ KB

In [63]:
#To be certain
data["Caffeine (mg)"].isnull().value_counts()

False    242
Name: Caffeine (mg), dtype: int64

In [64]:
#data preparation_3
#Drop unnecessary Columns
data = data.drop('Beverage_prep', axis=1)
#also I don't have the metadata of the dataset I think 'Beverage_prep' is the most unnecessary column

In [65]:
data.head()

,Beverage_category,Beverage,Calories,Total Fat (g),Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g),Vitamin A (% DV),Vitamin C (% DV),Calcium (% DV),Iron (% DV),Caffeine (mg)
0,Coffee,Brewed Coffee,3,0.1,0.0,0.0,0,5,0,0,0,0.3,0%,0%,0%,0%,175
1,Coffee,Brewed Coffee,4,0.1,0.0,0.0,0,10,0,0,0,0.5,0%,0%,0%,0%,260
2,Coffee,Brewed Coffee,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,0%,0%,330
3,Coffee,Brewed Coffee,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,2%,0%,410
4,Classic Espresso Drinks,Caffè Latte,70,0.1,0.1,0.0,5,75,10,0,9,6.0,10%,0%,20%,0%,75